[tool.poetry]
name = "proteapp"
version = "0.1.0"
description = "Mobile-first web application backend for the management of the 'Protectora de Animales y Plantas de Málaga'"
authors = ["Rafael Moret <rafaelmoretgalan@gmail.com>", "Cristina Espejo <cristinaespejoroque@outlook.es>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.111.0"
sqlmodel = "^0.0.19"
pydantic-extra-types = "^2.9.0"
phonenumbers = "^8.13.40"
docker = "^7.1.0"
beanie = "^1.26.0"
python-ulid = {extras = ["pydantic"], version = "^2.7.0"}
websockets = "^12.0"
pyjwt = "^2.9.0"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}

[tool.poetry.scripts]
start = "proteapp.__main__:start"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
