from datetime import datetime
from proteapp.models.animals import Sex

animales = [
    {
        "name": "Carolina",
        "description": "Carolina es una hermosa gata con un pelaje suave y lujoso. Disfruta tomando el sol y acurrucándose con sus compañeros humanos. A pesar de su apariencia regia, Carolina es increíblemente amigable y le encanta conocer gente nueva y otros animales.",
        "personality": "Amistosa y curiosa",
        "sex": Sex.female,
        "birthDate": datetime(2011, 10, 10),
        "entryDate": datetime(2022, 10, 9),
        "isCastrated": True,
        "isAnimalCompatible": True,
        "yard": "Patio 1",
        "hasTreatment": True,
        "image": 'https://cdn2.thecatapi.com/images/9vh.jpg',
        "id": 'f6b681ac-2b60-4b7d-a017-f490e8a8c10e'
    },
    {
        "name": "Luna",
        "description": "Luna es una gatita tímida y cariñosa. Prefiere pasar su tiempo acurrucada en una cama suave, pero una vez que se siente cómoda, le encanta recibir caricias y atención de sus seres queridos.",
        "personality": "Tímida y cariñosa",
        "sex": Sex.female,
        "birthDate": datetime(2018, 2, 28),
        "entryDate": datetime(2023, 1, 10),
        "isCastrated": True,
        "isAnimalCompatible": False,
        "yard": "Patio 1",
        "hasTreatment": True,
        "image": 'https://cdn2.thecatapi.com/images/def.jpg',
        "id": '51ccd7f1-65db-4dcd-86b3-2387b95d6900'
    },
    {
        "name": "Simón",
        "description": "Simón es un gato juguetón y enérgico. Le encanta correr por toda la casa persiguiendo juguetes y explorando cada rincón. Siempre está listo para una sesión de juego con su familia humana.",
        "personality": "Juguetón y enérgico",
        "sex": Sex.male,
        "birthDate": datetime(2019, 5, 15),
        "entryDate": datetime(2022, 12, 20),
        "isCastrated": False,
        "isAnimalCompatible": True,
        "yard": "Patio 2",
        "hasTreatment": False,
        "image": 'https://cdn2.thecatapi.com/images/abc.jpg',
        "id": '400bedd5-d77f-41af-86b7-82ee6d6fa8bf'
    },
    {
        "name": "Tiger",
        "description": "Tiger es un gato aventurero y valiente. Le encanta explorar los alrededores y nunca dice que no a una nueva aventura. Su coraje y espíritu intrépido lo hacen destacar entre los demás.",
        "personality": "Aventurero y valiente",
        "sex": Sex.male,
        "birthDate": datetime(2020, 7, 3),
        "entryDate": datetime(2023, 3, 22),
        "isCastrated": False,
        "isAnimalCompatible": False,
        "yard": "Patio inmuno",
        "hasTreatment": False,
        "image": 'https://cdn2.thecatapi.com/images/27r.jpg',
        "id": 'b7051f60-bff7-4cb9-b2a1-f559fd1abf6b'
    },
    {
        "name": "Mia",
        "description": "Mia es una gata tranquila y elegante. Disfruta pasar horas observando su entorno desde la ventana y relajarse en lugares cálidos y cómodos. Su gracia y calma son dignas de admiración.",
        "personality": "Tranquila y elegante",
        "sex": Sex.female,
        "birthDate": datetime(2017, 11, 20),
        "entryDate": datetime(2023, 6, 18),
        "isCastrated": True,
        "isAnimalCompatible": False,
        "yard": "Patio 4",
        "hasTreatment": True,
        "image": '',
        "id": '52f35395-0206-44c8-a456-44f0728b2b1c'
    },
    {
        "name": "Max",
        "description": "Max es un gato inteligente y leal. Siempre está atento a las necesidades de su familia humana y es rápido para ofrecer consuelo cuando lo necesitan. Su lealtad no tiene límites.",
        "personality": "Inteligente y leal",
        "sex": Sex.male,
        "birthDate": datetime(2016, 4, 12),
        "entryDate": datetime(2023, 9, 5),
        "isCastrated": False,
        "isAnimalCompatible": True,
        "yard": "Patio 1",
        "hasTreatment": True,
        "image": 'https://cdn2.thecatapi.com/images/afm.jpg',
        "id": 'f61f8574-ceaa-41a4-a3c3-d3d1ee9b175e'
    },
    {
        "name": "Lola",
        "description": "Lola es una gatita traviesa y juguetona. Siempre está buscando nuevas formas de divertirse y mantener entretenida a su familia humana. Su energía contagiosa ilumina cualquier habitación.",
        "personality": "Traviesa y juguetona",
        "sex": Sex.female,
        "birthDate": datetime(2021, 1, 8),
        "entryDate": datetime(2023, 11, 11),
        "isCastrated": True,
        "isAnimalCompatible": False,
        "yard": "Patio 2",
        "hasTreatment": False,
        "image": 'https://cdn2.thecatapi.com/images/pqr.jpg',
        "id": 'a2e167a6-f666-474c-b6c4-db7fb50417d8'
    },
    {
        "name": "Tomás",
        "description": "Tomás es un gato curioso y sociable. Siempre está interesado en lo que sucede a su alrededor y no duda en acercarse a nuevos amigos, tanto humanos como felinos. Su naturaleza amistosa lo convierte en el alma de la fiesta.",
        "personality": "Curioso y sociable",
        "sex": Sex.male,
        "birthDate": datetime(2015, 9, 25),
        "entryDate": datetime(2024, 2, 19),
        "isCastrated": True,
        "isAnimalCompatible": False,
        "yard": "Patio inmuno",
        "hasTreatment": True,
        "image": 'https://cdn2.thecatapi.com/images/58l.jpg',
        "id": 'cc0876bb-c981-4ff6-89f3-4e404b06b256'
    },
    {
        "name": "Molly",
        "description": "Molly es una gatita dulce y cariñosa. Le encanta pasar tiempo acurrucada en el regazo de sus seres queridos y recibir mimos y caricias. Su afecto incondicional es una fuente constante de alegría.",
        "personality": "Dulce y cariñosa",
        "sex": Sex.female,
        "birthDate": datetime(2014, 12, 3),
        "entryDate": datetime(2024, 4, 5),
        "isCastrated": True,
        "isAnimalCompatible": True,
        "yard": "Patio 3",
        "hasTreatment": False,
        "image": 'https://cdn2.thecatapi.com/images/MTg0NDAwNw.jpg',
        "id": '736b744f-b4f9-47ea-aa05-e4869f381395'
    },
    {
        "name": "Leo",
        "description": "Leo es un gato independiente y audaz. Disfruta explorando por su cuenta y no se intimida fácilmente ante lo desconocido. Su espíritu libre lo hace admirado por todos.",
        "personality": "Independiente y audaz",
        "sex": Sex.male,
        "birthDate": datetime(2013, 6, 17),
        "entryDate": datetime(2024, 5, 10),
        "isCastrated": True,
        "isAnimalCompatible": False,
        "yard": "Patio 4",
        "hasTreatment": False,
        "image": 'https://cdn2.thecatapi.com/images/MTg4ODgzNw.jpg',
        "id": '40fe9f90-0987-4bf1-9b3e-3f012286bc54'
    },
    {
        "name": "Lulu",
        "description": "Lola es una gatita enérgica y cariñosa. Siempre está lista para jugar y correr por la casa, pero también disfruta de largas siestas en el sol. Su personalidad versátil la hace amada por todos.",
        "personality": "Enérgica y cariñosa",
        "sex": Sex.female,
        "birthDate": datetime(2019, 8, 22),
        "entryDate": datetime(2024, 6, 15),
        "isCastrated": False,
        "isAnimalCompatible": False,
        "yard": "Patio 1",
        "hasTreatment": True,
        "image": 'https://cdn2.thecatapi.com/images/417.jpg',
        "id": 'bd92bf83-af55-4361-8d39-8aee67ec2ac6'
    },
    {
        "name": "Simba",
        "description": "Simba es un gato noble y protector. Siempre está vigilando su territorio y asegurándose de que su familia esté a salvo. Su coraje y devoción son incomparables.",
        "personality": "Noble y protector",
        "sex": Sex.male,
        "birthDate": datetime(2017, 3, 30),
        "entryDate": datetime(2024, 7, 20),
        "isCastrated": True,
        "isAnimalCompatible": False,
        "yard": "Patio inmuno",
        "hasTreatment": False,
        "image": 'https://cdn2.thecatapi.com/images/301.jpg',
        "id": '021392fe-d8bf-41fb-bc05-a0d6e476a8f0'
    }
]
